<a href="https://colab.research.google.com/github/HarshitManik/Thermalsensor/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
lst=[1,2,3,4,5,6,7]
%timeit [i**2 for i in lst]

2.47 µs ± 422 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
arr=np.array(lst)

In [ ]:
arr


array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
%timeit arr**2

714 ns ± 10.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [ ]:
arr +2


array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
# numpy basics
#np.array() fundamental elementts to arrange elements in an array
#np.arange()
l=[1,2,3,4,5,6,7,8]
np_arr= np.array(l)
type(np_arr)
np_arr.ndim
np_arr.shape

(8,)

In [ ]:
new_arr=np.arange(3,11)
new_arr
lst_2d=[[1,2,3],[4,5,6],[6,7,8]]
print(lst_2d)

[[1, 2, 3], [4, 5, 6], [6, 7, 8]]


In [ ]:
import numpy as np
new_arr=np.random.randint(10,100,(5,4))
print(new_arr)
print(new_arr[0,0])
print(new_arr[2,3])

[[31 21 44 17]
 [60 69 94 41]
 [79 40 39 56]
 [91 53 16 28]
 [19 85 39 50]]
31
56


In [ ]:
# masking
mask=new_arr>40
print(mask)

[[False False  True False]
 [ True  True  True  True]
 [ True False False  True]
 [ True  True False False]
 [False  True False  True]]


In [ ]:
#we can calculate the number of numbers greater than a specific number by simpy using the making feature
np.sum(mask)

11

In [ ]:
# to appen the array in the following manner use the following method
new_arr[2: , 2:]=0
print(new_arr)


NameError: name 'new_arr' is not defined

In [ ]:
np.transpose(new_arr)

NameError: name 'np' is not defined

In [4]:
import numpy as np
a=np.random.randint(0,10,(2,2))
a=np.random.randint(0,10,(2,2))


a.flatten()
print (a)

[[1 9]
 [7 5]]


In [1]:
a=[[1,2,3,4,5],
 [4,5,6,7,8],
   [8,9,1,2,3]]

In [2]:
print(a)

[[1, 2, 3, 4, 5], [4, 5, 6, 7, 8], [8, 9, 1, 2, 3]]


In [14]:
import numpy as np
a = np.array([[1, 2, 3, 4, 5],
              [4, 5, 6, 7, 8],
              [8, 9, 1, 2, 3]])
x=a.flatten()
print(x)
y=a.T
print(y)#transpose of a matrix
np.transpose(a)

[1 2 3 4 5 4 5 6 7 8 8 9 1 2 3]
[[1 4 8]
 [2 5 9]
 [3 6 1]
 [4 7 2]
 [5 8 3]]


array([[1, 4, 8],
       [2, 5, 9],
       [3, 6, 1],
       [4, 7, 2],
       [5, 8, 3]])

In [19]:
a=np.random.randint(0,10,(2,2))
b=np.random.randint(0,10,(2,2))
print(a)
print(b)
np.hstack((a,b))#horizontal stack
np.vstack((a,b))#vertical stack

[[0 7]
 [4 9]]
[[9 2]
 [7 5]]


array([[0, 7],
       [4, 9],
       [9, 2],
       [7, 5]])

In [ ]:
#BROADCASTING
